import { Annotation, Axis, Component, Crosshair, Grid, GroupComponent, HtmlComponent, Legend, Slider, Tooltip, Scrollbar } from '@antv/component';

export { ICanvas, IElement, IGroup, IShape } from '@antv/g-base/lib/interfaces';
export { PathCommand, BBox, Point, ShapeAttrs } from '@antv/g-base/lib/types';
export { Event, AbstractGroup, AbstractShape } from '@antv/g-base';
export type IG = any;
export { registerAdjust, getAdjust, Adjust } from '@antv/adjust/lib/factory';
export { getAttribute, Attribute } from '@antv/attr/lib/factory';
export { Color } from '@antv/attr';
export { getCoordinate, registerCoordinate, Coordinate, CoordinateCfg } from '@antv/coord';
export { getScale, registerScale, Scale, ScaleConfig } from '@antv/scale';
export { Tick } from '@antv/scale/lib/types';
export { IComponent, IList } from '@antv/component/lib/interfaces';
export { CategoryLegendCfg, CircleAxisCfg, LineAxisCfg, GroupComponentCfg, ListItem, AxisLineCfg, AxisTickLineCfg, AxisSubTickLineCfg, AxisTitleCfg, AxisLabelCfg, GridLineCfg, LegendMarkerCfg, LegendTitleCfg, LegendBackgroundCfg, LegendItemNameCfg, LegendItemValueCfg, ContinueLegendCfg, ContinueLegendTrackCfg, ContinueLegendRailCfg, ContinueLegendLabelCfg, ContinueLegendHandlerCfg, CrosshairLineCfg, CrosshairTextCfg, CrosshairTextBackgroundCfg, SliderCfg, TrendCfg, EnhancedTextCfg, LineAnnotationTextCfg, } from '@antv/component/lib/types';
export { HtmlComponent, GroupComponent, Component, Crosshair };
export { Annotation };
export type  LineAxis = typeof Axis.Line;
export type  CircleAxis = typeof Axis.Circle;
export type LineGrid = typeof Grid.Line;
export type CircleGrid = typeof Grid.Circle;
type CategoryLegend = typeof Legend.Category;
type ContinuousLegend = typeof Legend.Continuous;
export { CategoryLegend, ContinuousLegend };
type HtmlTooltip = typeof Tooltip.Html;
export { HtmlTooltip };
export { Slider };
export { Scrollbar };
