module.exports = {
  TABS: ['基本属性', '偏好习惯', '消费行为'],
  PANEL0: [
    { key: 'age', type: 'smoothbar', title: '年龄分布' },
    { key: 'sex', type: 'cyclic', title: '性别分布' },
    { key: 'star', type: 'circlecloud', title: '星座分布' },
    { key: 'city', type: 'pie', title: '城市级别' },
    { key: 'level', type: 'histogram', title: '人生阶段' },
    { key: 'finish', type: 'pie', title: '是否处于装修期' },
    { key: 'house', type: 'pie', title: '是否有房' },
    { key: 'car', type: 'pie', title: '是否有车' },
    { key: 'babyage', type: 'cyclic', title: '宝宝年龄' },
    { key: 'pet', type: 'pie', title: '是否养宠物' },
    { key: 'student', type: 'pie', title: '是否大学生' },
    { key: 'education', type: 'cyclic', title: '学历' },
    { key: 'occupation', type: 'histogram', title: '职业', oneline: true },
  ],
  PANEL1: [
    { key: 'brand', type: 'horizonNoLabel', title: '全网品牌偏好' },
    { key: 'brand', type: 'horizonNoLabel', title: '一级类目品牌偏好' },
    { key: 'brand', type: 'horizonNoLabel', title: '叶子类目品牌偏好' },
    { key: 'brand', type: 'horizonNoLabel', title: '一级类目购买偏好' },
    { key: 'brand', type: 'horizonNoLabel', title: '叶子类目购买偏好' },
    { key: 'hobby', type: 'star', title: '兴趣爱好' },
    { key: 'age', type: 'pie', title: '折扣敏感度' },
  ],
  PANEL2: [
    { key: 'buyerstar', type: 'smoothbar', title: '淘宝买家星级', oneline: true },
    { key: 'tblevel', type: 'horizon', title: '淘宝会员等级' },
    { key: 'tmlevel', type: 'horizon', title: '天猫会员等级' },
    { key: 'highlevel', type: 'pie', title: '淘宝高端买家' },
    { key: 'consumelevel', type: 'profession', title: '消费层级' },
    { key: 'accecption', type: 'horizon', title: '可接受价格带' },
    { key: 'buy', type: 'horizon', title: '近90天购买频率' },
    { key: 'consume', type: 'horizon', title: '近90天消费金额', oneline: true },
  ],
};
